module.exports = {
    apiHost : 'yzsoc001.kmdns.net',
    apiPort : '18080',
    domain : "",
    apiPath : 'service/ldo',
    fileRelativePath : 'boxplatform/upload',
    imgUrl:'http://116.62.138.223:8080/serverimages/',
    newsPath : 'news',
    organizationPath : 'organization',
    dailystarPath : 'dailystar',
    talenttypePath : 'talenttype',
    talentPath : 'talent',
    committeePath : 'committee',
    hallPath : 'hall',
    goodsPath : 'goods',
    adPath : 'ad_code',
    userPath : 'user',
    redisPort : 6379,
    needConsole : true,
    sign : 'yztx',
    wechatPath : 'ewm',
    redisPass:'yz123qwe',
    redisHost: "192.168.0.60",
    accounttypestore:['5','6','7','8','9','10'],
    accounttypecard:['3','4']
};